//Created at 07:44:12 AM CET
//Code generated by Techne Online Java Extractor written by The_Nuclear_Option

package mooklabs.nausicaamod.mobs.flying;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDragonfly extends ModelBase
{
	ModelRenderer Shape1_0;
	ModelRenderer lfwing_1;
	ModelRenderer Shape3_2;
	ModelRenderer Shape4_3;
	ModelRenderer Shape5_4;
	ModelRenderer rjaw_5;
	ModelRenderer ljaw_6;
	ModelRenderer tail1_7;
	ModelRenderer tail2_8;
	ModelRenderer Shape10_9;
	ModelRenderer Shape11_10;
	ModelRenderer Shape12_11;
	ModelRenderer Shape13_12;
	ModelRenderer Shape14_13;
	ModelRenderer Shape15_14;
	ModelRenderer Shape16_15;
	ModelRenderer Shape17_16;
	ModelRenderer Shape18_17;
	ModelRenderer Shape19_18;
	ModelRenderer Shape20_19;
	ModelRenderer Shape21_20;
	ModelRenderer Shape22_21;
	ModelRenderer Shape23_22;
	ModelRenderer lrwing_23;
	ModelRenderer rfwing_24;
	ModelRenderer rrwing_25;

	public ModelDragonfly()
	{
		textureWidth = 64;
		textureHeight = 64;
		Shape1_0 = new ModelRenderer(this,0,0);
		Shape1_0.addBox(0.0F,0.0F,0.0F,5,4,7);
		Shape1_0.setRotationPoint(0.0F,16.0F,0.0F);
		Shape1_0.setTextureSize(128,256);
		Shape1_0.mirror = false;
		setRotation(Shape1_0,0.0F,0.0F,0.0F);

		lfwing_1 = new ModelRenderer(this,0,33);
		lfwing_1.addBox(0.0F,0.0F,0.0F,10,1,3);
		lfwing_1.setRotationPoint(5.0F,16.0F,1.0F);
		lfwing_1.setTextureSize(128,256);
		lfwing_1.mirror = false;
		setRotation(lfwing_1,0.0F,28.0F,0.0F);

		Shape3_2 = new ModelRenderer(this,0,13);
		Shape3_2.addBox(-2.0F,0.0F,-4.0F,4,3,4);
		Shape3_2.setRotationPoint(2.5F,16.0F,-1.0F);
		Shape3_2.setTextureSize(128,256);
		Shape3_2.mirror = false;
		setRotation(Shape3_2,28.0F,0.0F,0.0F);

		Shape4_3 = new ModelRenderer(this,9,21);
		Shape4_3.addBox(0.0F,0.0F,0.0F,1,2,3);
		Shape4_3.setRotationPoint(1.0F,18.0F,-6.0F);
		Shape4_3.setTextureSize(128,256);
		Shape4_3.mirror = false;
		setRotation(Shape4_3,28.0F,10.0F,0.0F);

		Shape5_4 = new ModelRenderer(this,0,21);
		Shape5_4.addBox(0.0F,0.0F,0.0F,1,2,3);
		Shape5_4.setRotationPoint(3.0F,18.0F,-6.0F);
		Shape5_4.setTextureSize(128,256);
		Shape5_4.mirror = false;
		setRotation(Shape5_4,28.0F,-10.0F,0.0F);

		rjaw_5 = new ModelRenderer(this,0,27);
		rjaw_5.addBox(-1.0F,0.0F,0.0F,1,3,1);
		rjaw_5.setRotationPoint(2.0F,19.0F,-5.0F);
		rjaw_5.setTextureSize(128,256);
		rjaw_5.mirror = false;
		setRotation(rjaw_5,25.0F,10.0F,0.0F);

		ljaw_6 = new ModelRenderer(this,5,27);
		ljaw_6.addBox(0.0F,0.0F,0.0F,1,3,1);
		ljaw_6.setRotationPoint(3.0F,19.0F,-5.0F);
		ljaw_6.setTextureSize(128,256);
		ljaw_6.mirror = false;
		setRotation(ljaw_6,25.0F,-10.0F,0.0F);

		tail1_7 = new ModelRenderer(this,25,0);
		tail1_7.addBox(-1.0F,0.0F,0.0F,3,3,7);
		tail1_7.setRotationPoint(2.0F,16.0F,7.0F);
		tail1_7.setTextureSize(128,256);
		tail1_7.mirror = false;
		setRotation(tail1_7,0.0F,0.0F,0.0F);

		tail2_8 = new ModelRenderer(this,25,11);
		tail2_8.addBox(0.0F,0.0F,0.0F,1,2,9);
		tail2_8.setRotationPoint(2.0F,16.0F,14.0F);
		tail2_8.setTextureSize(128,256);
		tail2_8.mirror = false;
		setRotation(tail2_8,0.0F,0.0F,0.0F);

		Shape10_9 = new ModelRenderer(this,23,0);
		Shape10_9.addBox(-1.0F,0.0F,0.0F,1,4,1);
		Shape10_9.setRotationPoint(1.0F,18.0F,0.0F);
		Shape10_9.setTextureSize(128,256);
		Shape10_9.mirror = false;
		setRotation(Shape10_9,-16.0F,0.0F,20.0F);

		Shape11_10 = new ModelRenderer(this,40,0);
		Shape11_10.addBox(0.0F,0.0F,-4.0F,1,1,4);
		Shape11_10.setRotationPoint(-1.0F,21.0F,0.0F);
		Shape11_10.setTextureSize(128,256);
		Shape11_10.mirror = false;
		setRotation(Shape11_10,0.0F,0.0F,0.0F);

		Shape12_11 = new ModelRenderer(this,18,12);
		Shape12_11.addBox(-1.0F,0.0F,0.0F,1,3,1);
		Shape12_11.setRotationPoint(0.0F,21.0F,-4.0F);
		Shape12_11.setTextureSize(128,256);
		Shape12_11.mirror = false;
		setRotation(Shape12_11,0.0F,0.0F,-11.0F);

		Shape13_12 = new ModelRenderer(this,18,0);
		Shape13_12.addBox(0.0F,0.0F,0.0F,1,4,1);
		Shape13_12.setRotationPoint(4.0F,18.0F,0.0F);
		Shape13_12.setTextureSize(128,256);
		Shape13_12.mirror = false;
		setRotation(Shape13_12,-16.0F,0.0F,-20.0F);

		Shape14_13 = new ModelRenderer(this,51,0);
		Shape14_13.addBox(0.0F,0.0F,-4.0F,1,1,4);
		Shape14_13.setRotationPoint(5.0F,21.0F,0.0F);
		Shape14_13.setTextureSize(128,256);
		Shape14_13.mirror = false;
		setRotation(Shape14_13,0.0F,0.0F,0.0F);

		Shape15_14 = new ModelRenderer(this,13,12);
		Shape15_14.addBox(0.0F,0.0F,0.0F,1,3,1);
		Shape15_14.setRotationPoint(5.0F,21.0F,-4.0F);
		Shape15_14.setTextureSize(128,256);
		Shape15_14.mirror = false;
		setRotation(Shape15_14,0.0F,0.0F,11.0F);

		Shape16_15 = new ModelRenderer(this,9,53);
		Shape16_15.addBox(0.0F,0.0F,0.0F,3,1,1);
		Shape16_15.setRotationPoint(5.0F,19.5F,3.0F);
		Shape16_15.setTextureSize(128,256);
		Shape16_15.mirror = false;
		setRotation(Shape16_15,0.0F,0.0F,37.0F);

		Shape17_16 = new ModelRenderer(this,0,56);
		Shape17_16.addBox(0.0F,0.0F,0.0F,1,3,1);
		Shape17_16.setRotationPoint(6.0F,21.0F,3.0F);
		Shape17_16.setTextureSize(128,256);
		Shape17_16.mirror = false;
		setRotation(Shape17_16,0.0F,0.0F,0.0F);

		Shape18_17 = new ModelRenderer(this,0,53);
		Shape18_17.addBox(-3.0F,0.0F,0.0F,3,1,1);
		Shape18_17.setRotationPoint(0.0F,19.5F,3.0F);
		Shape18_17.setTextureSize(128,256);
		Shape18_17.mirror = false;
		setRotation(Shape18_17,0.0F,0.0F,-37.0F);

		Shape19_18 = new ModelRenderer(this,5,56);
		Shape19_18.addBox(-1.0F,0.0F,0.0F,1,3,1);
		Shape19_18.setRotationPoint(-1.0F,21.0F,3.0F);
		Shape19_18.setTextureSize(128,256);
		Shape19_18.mirror = false;
		setRotation(Shape19_18,0.0F,0.0F,0.0F);

		Shape20_19 = new ModelRenderer(this,9,61);
		Shape20_19.addBox(0.0F,0.0F,0.0F,3,1,1);
		Shape20_19.setRotationPoint(4.0F,19.5F,6.0F);
		Shape20_19.setTextureSize(128,256);
		Shape20_19.mirror = false;
		setRotation(Shape20_19,0.0F,-37.0F,29.0F);

		Shape21_20 = new ModelRenderer(this,0,61);
		Shape21_20.addBox(0.0F,0.0F,0.0F,3,1,1);
		Shape21_20.setRotationPoint(1.5F,19.5F,7.0F);
		Shape21_20.setTextureSize(128,256);
		Shape21_20.mirror = false;
		setRotation(Shape21_20,0.0F,-137.0F,29.0F);

		Shape22_21 = new ModelRenderer(this,0,0);
		Shape22_21.addBox(0.0F,0.0F,0.0F,1,3,1);
		Shape22_21.setRotationPoint(-1.0F,21.0F,7.5F);
		Shape22_21.setTextureSize(128,256);
		Shape22_21.mirror = false;
		setRotation(Shape22_21,0.0F,0.0F,0.0F);

		Shape23_22 = new ModelRenderer(this,0,13);
		Shape23_22.addBox(0.0F,0.0F,0.0F,1,3,1);
		Shape23_22.setRotationPoint(5.0F,21.0F,7.5F);
		Shape23_22.setTextureSize(128,256);
		Shape23_22.mirror = false;
		setRotation(Shape23_22,0.0F,0.0F,0.0F);

		lrwing_23 = new ModelRenderer(this,0,38);
		lrwing_23.addBox(0.0F,0.0F,-3.0F,10,1,3);
		lrwing_23.setRotationPoint(5.0F,16.0F,6.0F);
		lrwing_23.setTextureSize(128,256);
		lrwing_23.mirror = false;
		setRotation(lrwing_23,0.0F,-22.0F,0.0F);

		rfwing_24 = new ModelRenderer(this,0,48);
		rfwing_24.addBox(-10.0F,0.0F,0.0F,10,1,3);
		rfwing_24.setRotationPoint(0.0F,16.0F,1.0F);
		rfwing_24.setTextureSize(128,256);
		rfwing_24.mirror = false;
		setRotation(rfwing_24,0.0F,-28.0F,0.0F);

		rrwing_25 = new ModelRenderer(this,0,43);
		rrwing_25.addBox(-10.0F,0.0F,-3.0F,10,1,3);
		rrwing_25.setRotationPoint(0.0F,16.0F,6.0F);
		rrwing_25.setTextureSize(128,256);
		rrwing_25.mirror = false;
		setRotation(rrwing_25,0.0F,22.0F,0.0F);

	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Shape1_0.render(f5);
		lfwing_1.render(f5);
		Shape3_2.render(f5);
		Shape4_3.render(f5);
		Shape5_4.render(f5);
		rjaw_5.render(f5);
		ljaw_6.render(f5);
		tail1_7.render(f5);
		tail2_8.render(f5);
		Shape10_9.render(f5);
		Shape11_10.render(f5);
		Shape12_11.render(f5);
		Shape13_12.render(f5);
		Shape14_13.render(f5);
		Shape15_14.render(f5);
		Shape16_15.render(f5);
		Shape17_16.render(f5);
		Shape18_17.render(f5);
		Shape19_18.render(f5);
		Shape20_19.render(f5);
		Shape21_20.render(f5);
		Shape22_21.render(f5);
		Shape23_22.render(f5);
		lrwing_23.render(f5);
		rfwing_24.render(f5);
		rrwing_25.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
}